### ISSUE TITLE
Push 0.19.0 to crates.io with the updated dependencies

### ISSUE THREAD

**Issue by Machtan** [xsleonard/rust-sdl2_image#68]
The current valid version on crates.io (0.18) has a dependency on an outdated version of sdl2-sys (0.8.1), which results in a dependency error when using other SDL libraries.

It looks like the version here on github has the correct dependencies set, so the only required change should be bumping the version in the cargofile :).

The dependency can be seen [here](https://crates.io/crates/sdl2_image/0.18.0).

For reference, the error I get is this:
```
error: native library `SDL2` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  sdl2-sys v0.19.0
  sdl2-sys v0.8.1
```

**Comment by Emiluren** [comment]
It seems like the current version on crates.io has a similar problem. It depends on sdl2 0.19 but the github version depends on 0.20 but still has the version 0.19. If you try to use this:
`[dependencies]
sdl2 = "0.20"
sdl2_image = "0.19"`
you will get an error about
`src\main.rs:23:28: 23:40 error: no method named `load_texture` found int the current scope
src\main.rs:23     let texture = renderer.load_texture(png).unwrap();`
The same problem as #50. Can be fixed by referencing the repository directly.
